name: feature-flipper
version: '0.1.0.0'
category: Web
author: Todd Mohney
maintainer: toddmohney@gmail.com
copyright: 2017 Todd Mohney
license: BSD3
github: toddmohney/feature-flipper
extra-source-files:
- README.md
library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - Flipper
  dependencies:
  - base >=4.7 && <5
  - containers
  - mtl
  - text
tests:
  feature-flipper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    dependencies:
    - base
    - containers
    - feature-flipper
    - hspec
    - mtl
    - QuickCheck
    other-modules:
    - FlipperSpec
