name: feature-flipper
version: '0.2.0.1'
synopsis: A minimally obtrusive feature flag library
description: A minimally obtrusive feature flag library
category: Web
author: Todd Mohney
maintainer: toddmohney@gmail.com
copyright: 2017 Todd Mohney
license: MIT
github: toddmohney/flipper
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-unused-matches
  - -fwarn-unused-binds
  - -fwarn-unused-imports
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - Control.Flipper
  - Control.Flipper.Types
  - Control.Flipper.Adapters.Memory
  dependencies:
  - base >=4.8 && <5
  - containers
  - data-default
  - digest
  - mtl
  - text
tests:
  feature-flipper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    dependencies:
    - base
    - bytestring
    - containers
    - data-default
    - digest
    - feature-flipper
    - hspec
    - mtl
    other-modules:
    - Control.FlipperSpec
