packages:
- '.'
- examples/environment-config
- examples/enable-feature-for-a-specific-user

resolver: lts-8.14

extra-deps: []

flags: {}

extra-package-dbs: []

ghc-options:
  feature-flipper: -Wall -Werror -fno-warn-warnings-deprecations
