name: environment-config
version: '0.1.0.0'
synopsis: Examples of feature-flipper usage patterns
description: Examples of feature-flipper usage patterns
category: Web
author: Todd Mohney
maintainer: toddmohney@gmail.com
copyright: 2017 Todd Mohney
license: MIT
github: toddmohney/feature-flipper
extra-source-files:
- README.md
executables:
  environment-config:
      main: Main.hs
      source-dirs: .
      ghc-options:
      - -Wall
      - -fwarn-unused-matches
      - -fwarn-unused-binds
      - -fwarn-unused-imports
      default-extensions:
      - OverloadedStrings
      dependencies:
      - base >=4.8 && <5
      - containers
      - data-default
      - feature-flipper
      - mtl
